#!/bin/sh
if [ -n "$WWWUSER" ]; then
    echo "usermod run"
    usermod -u $WWWUSER sail
fi

if [ -n "$WWWGROUP" ]; then
    echo "groupmod run"
    groupmod -g $WWWGROUP sail
fi

if [ ! -d /.composer ]; then
    mkdir /.composer
fi

chmod -R ugo+rw /.composer
webserver=${WEBSERVER:-cli}

if [ "$webserver" = "cli" ]; then
  export ENV_SUPERVISOR_PHP_COMMAND="/usr/bin/php -d variables_order=EGPCS /var/www/html/artisan serve --host=0.0.0.0 --port=80"
  elif [ "$webserver" = "octane" ]; then
  export ENV_SUPERVISOR_PHP_COMMAND="/usr/bin/php -d variables_order=EGPCS /var/www/html/artisan octane:start --host=0.0.0.0 --port=80"
  elif [ "$webserver" = "octane-watch" ]; then
  export ENV_SUPERVISOR_PHP_COMMAND="/usr/bin/php -d variables_order=EGPCS /var/www/html/artisan octane:start --watch --host=0.0.0.0 --port=80"
fi

if [ $# -gt 0 ]; then
    exec gosu $WWWUSER "$@"
else
    exec /usr/bin/supervisord -c /etc/supervisor/conf.d/supervisor.conf
fi