name: Publish Docker
on:
  workflow_call:
  push:
    branches:
      - main
  schedule:
    - cron: 0 0 * * 3
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    strategy::
        fail-fast: false
        matrix:
          include:
            - dockerfile: ./runtimes/7.4/Dockerfile
              tags: ariaieboy/sail-runtime-image:7.4
            - dockerfile: ./runtimes/8.0/Dockerfile
              tags: ariaieboy/sail-runtime-image:8.0
            - dockerfile: ./runtimes/8.1/Dockerfile
              tags: ariaieboy/sail-runtime-image:8.1
            - dockerfile: ./runtimes/8.2/Dockerfile
              tags: ariaieboy/sail-runtime-image:8.2
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v4
        with:
          platforms: linux/amd64,linux/arm64
          context: .
          file: ${{ matrix.dockerfile }}
          push: true
          tags: ${{ matrix.tags }}