name: Publish Docker
on:
  workflow_dispatch:
  push:
    branches: ['main']
    paths: ['runtimes/**']
  schedule:
    - cron: 0 0 * * 3
jobs:
  push:
    runs-on: ubuntu-latest
    strategy:
        fail-fast: false
        matrix:
            php: ['8.0','8.1','8.2']
            node: ['18','20']
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push Node 20
        if: ${{ matrix.node }} == 20
        uses: docker/build-push-action@v4
        with:
          platforms: linux/amd64,linux/arm64
          context: ./runtimes/common
          file: ./runtimes/${{ matrix.php }}/Dockerfile
          push: true
          build-args: NODE_VERSION=${{ matrix.node }}
          tags: ariaieboy/sail-runtime-image:${{ matrix.php }}-${{ matrix.node }},ariaieboy/sail-runtime-image:${{ matrix.php }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
      -
        name: Build and push Node 18
        if: ${{ matrix.node }} == 18
        uses: docker/build-push-action@v4
        with:
          platforms: linux/amd64,linux/arm64
          context: ./runtimes/common
          file: ./runtimes/${{ matrix.php }}/Dockerfile
          push: true
          build-args: NODE_VERSION=${{ matrix.node }}
          tags: ariaieboy/sail-runtime-image:${{ matrix.php }}-${{ matrix.node }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
